paths:
  /apis/auth/register:
    post:
      summary: "Allows the user to register an account."
      description: "Allows the user to register an account on the website."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: "email@email.com"
                username:
                  type: string
                  example: "marysue"
                password:
                  type: string
                  format: password
                  example: "password123"
      responses:
        201:
          description: User successfully registered.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "User registered successfully."
        400:
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid input data."
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Internal server error."

  /apis/auth/login:
    post:
      sumarry: "Allows the user to login."
      description: "Allows the user to login to the website."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: "user123"
                email:
                  type: string
                  format: email
                  example: "user@example.com"
                password:
                  type: string
                  format: password
                  example: "securepassword"
              required:
                - password
              oneOf:
                - required: [username]
                - required: [email]
              additionalProperties: false
            # schema:
            #   type: object
            #   properties:
            #     username:
            #       type: string
            #       example: "marysue"
            #     email:
            #       type: string
            #       format: email
            #       example: "email@email.com"
            #     password:
            #       type: string
            #       format: password
            #       example: "password123"
            # required:
            #   - password
            # oneOf:
            #   - required: [username]
            #   - required: [email]
            # additionalProperties: false

      responses:
        200:
          description: User successfully logged in.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Login successfully."
        400:
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Please enter username/email and password!"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid username or password."
        404:
          description: Not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "User not found!"
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Internal server error."
